# Projeto Forecast — 01. Ingestão dos dados

Carrega o `world_population.csv` (separador `;`, UTF-8) para um DataFrame.

In [1]:
import pandas as pd
from pathlib import Path

CAMINHO_CSV = Path('data') / 'world_population.csv'

In [2]:
df = pd.read_csv(CAMINHO_CSV, sep=';', encoding='utf-8')
print(f'{df.shape[0]} linhas x {df.shape[1]} colunas')
df.head()

234 linhas x 17 colunas

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,630.587,10.2570,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,988.702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,188.531,10.1640,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,2.224.774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,1.705.641,1.0100,0.00

## Estrutura e tipos

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         234 non-null    int64
 1   CCA3                         234 non-null    object
 2   Country/Territory            234 non-null    object
 3   Capital                      234 non-null    object
 4   Continent                    234 non-null    object
 5   2022 Population              234 non-null    int64
 6   2020 Population              234 non-null    int64
 7   2015 Population              234 non-null    int64
 8   2010 Population              234 non-null    int64
 9   2000 Population              234 non-null    int64
 10  1990 Population              234 non-null    int64
 11  1980 Population              234 non-null    int64
 12  1970 Population              234 non-null    int64
 13  Area (km²)                   234 non-null    int64
 14  Density (per km²)            234 non-null    object
 15  Growth Rate                  234 non-null    float64
 16  World Population Percentage  234 non-null    float64
dtypes: float64(2), int64(10), object(5)
memory usage: 31.2+ KB

## Valores nulos e duplicados

In [4]:
print('Nulos por coluna:')
print(df.isna().sum())
print()
print('Linhas duplicadas:', df.duplicated().sum())
print('Países duplicados (CCA3):', df['CCA3'].duplicated().sum())

Nulos por coluna:
Rank                           0
CCA3                           0
Country/Territory              0
Capital                        0
Continent                      0
2022 Population                0
2020 Population                0
2015 Population                0
2010 Population                0
2000 Population                0
1990 Population                0
1980 Population                0
1970 Population                0
Area (km²)                     0
Density (per km²)              0
Growth Rate                    0
World Population Percentage    0
dtype: int64

Linhas duplicadas: 0
Países duplicados (CCA3): 0

## Atenção: colunas decimais vieram corrompidas

`Density (per km²)` e `Growth Rate` perderam a vírgula decimal na exportação — os pontos viraram separadores de milhar:

- Densidade do Afeganistão `630.587` deveria ser ~63,06; Samoa Americana `2.224.774` deveria ser ~222,48 (por isso a coluna é lida como texto).
- Taxa de crescimento `10.257` deveria ser `1.0257` (valores abaixo de 1, como `0.9957`, estão corretos).

`World Population Percentage` parece correta. Vamos tratar isso na etapa de limpeza.

In [5]:
cols_suspeitas = ['Density (per km²)', 'Growth Rate', 'World Population Percentage']
df[['Country/Territory', '2022 Population', 'Area (km²)'] + cols_suspeitas].head(10)

,Country/Territory,2022 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,41128771,652230,630.587,10.2570,0.52
1,Albania,2842321,28748,988.702,0.9957,0.04
2,Algeria,44903225,2381741,188.531,10.1640,0.56
3,American Samoa,44273,199,2.224.774,0.9831,0.00
4,Andorra,79824,468,1.705.641,1.0100,0.00
5,Angola,35588987,1246700,285.466,10.3150,0.45
6,Anguilla,15857,91,1.742.527,10.0660,0.00
7,Antigua and Barbuda,93763,442,2.121.335,10.0580,0.00
8,Argentina,45510318,2780400,163.683,10.0520,0.57
9,Armenia,2780469,29743,934.831,0.9962,0.03